translate::appendix-01::1-133
rust-lang-th/book-th pull request #11
Opened 2021-06-06 08:08 UTC by ARMnunf

- [ ] The PR is involve only 1 chapter at most.
- [ ] The PR title conforms to the recommended [templates](https://github.com/rust-lang-th/book-th/blob/master/CONTRIBUTING.md#commit-message).
- [ ] The PR has short description about what you has been done
- [ ] Please make sure the layout of the page after you translate looks fantastic by checking from [running the book locally.](https://github.com/rust-lang-th/book-th#building)

Change detail:

translate::appendix-01::1-133

2021-06-11 12:18 UTC, ARMnunf commented
ครับ

2021-06-11 12:50 UTC, nsuthison commented
> ครับ

Sry for my late reply krub, I'll review it with in today.

2021-06-12 06:58 UTC, dodadoa requested changes
คิดว่ามีแก้นิดหน่อยฮะพวก typo กับมีตรง captures นิดหน่อย คิดว่าตรงนั้นแปลลงไปได้เลยฮะ นอกนั้นไม่มีติดอะไรครับผม

2021-06-12 06:58 UTC, dodadoa commented on src/appendix-01-keywords.md
> +* `move` - ทำให้ closure รับความเป็นเจ้าของ (ownership) ของ captures ทั้งหมด
ตรง ของ captures ทั้งหมด จริงๆแล้วตรงนี้แปลไปเลยก็ได้มั้งฮะ captures ไม่น่าจะเป็นคำเฉพาะหรือเปล่าหว่า

2021-06-12 06:58 UTC, dodadoa commented on src/appendix-01-keywords.md
> +ตัวอย่างเช่น `match` เป็นคีย์เวิร์ด ถ้าคุณฦลองคอมไพล์ฟังก์ชันเหล่านี้
มี typo ตรง `คุณฦ`

2021-06-12 06:58 UTC, dodadoa commented on src/appendix-01-keywords.md
> +และมีฟังก์ชัน `try` คุณจำเป็นจะต้องใช้ raw identifier syntax `r#try` in
typo ตรง `in` ฮะ เหมือนแปลไว้แล้วข้างล่างตรง `ในกรณี`

2021-06-12 10:45 UTC, nsuthison requested changes

2021-06-12 10:45 UTC, nsuthison commented on src/appendix-01-keywords.md
> +## ภาคผนวก A: คีย์เวิร์ด
Might be better if we translate `keywords` to `คำสำคัญ` instead of `คีย์เวิร์ด`

2021-06-12 10:45 UTC, nsuthison commented on src/appendix-01-keywords.md
> +ฟังก์ชัน, ตัวแปร, พารามิเตอร์, struct fields, โมดูล, crates, ค่าคงที่,
ฟังก์ชัน, ตัวแปร, พารามิเตอร์, โมดูล, ค่าคงที่ นี่ ผมว่าทับศัพท์ไปเลยน่าจะดีกว่าไหมครับ

2021-06-12 10:45 UTC, nsuthison commented on src/appendix-01-keywords.md
> +* `async` -  คืนค่า `Future` แทนที่จะบล็อกเธรด (Thread) ปัจจุบัน
ตรงนี้ผมคิดว่า Thread ทับศํพท์ไปเลยน่าจะดีกว่าครับ

2021-06-12 10:45 UTC, nsuthison commented on src/appendix-01-keywords.md
> +แม้ว่าคำนั้นจะเป็นคีย์เวิร์ดที่สงวนไว้ก็ตาม นอจากนี้ raw identifiers
นอจากนี้ -> นอกจากนี้

2021-06-12 10:45 UTC, nsuthison commented on src/appendix-01-keywords.md
> +คุณจะได้รับข้อผิดพลาดนี้:
อันนี้โดยส่วนตัวคิดว่าถ้าแปลเป็น `คุณจะได้รับ error:` น่าจะอ่านง่ายกว่าคำว่าข้อผิดพลาด

2021-06-12 21:19 UTC, enwuft commented on src/appendix-01-keywords.md
> +## ภาคผนวก A: คีย์เวิร์ด
หรือเป็น **คำสงวน** ดีครับ ผมก็ไม่เเน่ใจ

2021-06-13 04:13 UTC, ARMnunf commented on src/appendix-01-keywords.md
> +* `move` - ทำให้ closure รับความเป็นเจ้าของ (ownership) ของ captures ทั้งหมด
ผมควรเขียนทับศัพท์หรือว่าควรแปลเป็นไทยว่าอะไรดีครับ

2021-06-13 04:22 UTC, ARMnunf commented
ผมว่าเราควรจะเพิ่มไฟล์ดิกชันนารีเอาไว้จะดีมั้ยครับ เพื่อให้จะได้แปลไปในทิศทางเดียวกัน และคนอ่านสับสนว่าคำนี้ในภาษาอังกฤษคืออะไรก็จะได้มาหาในไฟล์นี้ได้

2021-06-14 10:15 UTC, dodadoa commented
> ผมว่าเราควรจะเพิ่มไฟล์ดิกชันนารีเอาไว้จะดีมั้ยครับ เพื่อให้จะได้แปลไปในทิศทางเดียวกัน และคนอ่านสับสนว่าคำนี้ในภาษาอังกฤษคืออะไรก็จะได้มาหาในไฟล์นี้ได้

เห็นด้วยครับ จะได้มีแนวทางวางไว้ด้วยว่าคำนี้ควรทับศัพท์หรือแปลทับศัพท์หรือแปลไปเลยดี
cc: @nsuthison

2021-06-14 14:34 UTC, nsuthison commented on src/appendix-01-keywords.md
> +## ภาคผนวก A: คีย์เวิร์ด
คำสงวนก็น่าจะดีนะครับ @dodadoa มีความเห็นมั้ยครับ?

2021-06-14 14:34 UTC, nsuthison commented
> > ผมว่าเราควรจะเพิ่มไฟล์ดิกชันนารีเอาไว้จะดีมั้ยครับ เพื่อให้จะได้แปลไปในทิศทางเดียวกัน และคนอ่านสับสนว่าคำนี้ในภาษาอังกฤษคืออะไรก็จะได้มาหาในไฟล์นี้ได้
> 
> เห็นด้วยครับ จะได้มีแนวทางวางไว้ด้วยว่าคำนี้ควรทับศัพท์หรือแปลทับศัพท์หรือแปลไปเลยดี
> cc: @nsuthison

เห็นด้วยครับ!

2021-07-03 15:09 UTC, aunpyz commented on src/appendix-01-keywords.md
> +## ภาคผนวก A: คีย์เวิร์ด
@enwuft **คำสงวน** น่าจะเก็บไว้ใช้กับ reserved (key)words ดีกว่าไหมครับ?
ไม่งั้นตรงบรรทัด https://github.com/rust-lang-th/book-th/blob/master/src/appendix-01-keywords.md#keywords-reserved-for-future-use เราก็ต้องหาคำแปลใหม่ลดความซ้ำซ้อนของคำแปลเดิมที่เคยแปลไว้

> `### คีย์เวิร์ดที่สงวนไว้สำหรับการใช้งานในอนาคต` -> `### **คำสงวน**ที่สงวนไว้สำหรับการใช้งานในอนาคต`

2021-07-08 14:08 UTC, ARMnunf commented on src/appendix-01-keywords.md
> +## ภาคผนวก A: คีย์เวิร์ด
งั้นผมขอใช้คำว่า คีเวิร์ด ทับศัพท์สำหรับ Keywords และใช้คำว่า คำสงวน สำหรับ reserved keywords นะครับ

2024-06-24 03:49 UTC, closed without merging